excerpt_separator: ""
pygments: true
markdown: kramdown

url: http://ryabov.xyz
title: Sergey Ryabov's blog
email: colriot@gmail.com
author: Sergey Ryabov
description: May the Code be with you
paginate: 10

disqus_shortname: colriot
google_analytics: UA-65545201-1